import { useEffect, useState } from "react";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { supabase } from "@/integrations/supabase/client";
import { Loader2, Bell, Check, AlertTriangle } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export default function RiskAlerts() {
  const { toast } = useToast();
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(false);
  const [alerts, setAlerts] = useState<any[]>([]);

  const fetchAll = async () => {
    setLoading(true);
    const { data } = await supabase.from("risk_alerts").select("*").order("created_at", { ascending: false }).limit(200);
    setAlerts(data || []);
    setLoading(false);
  };
  useEffect(() => { fetchAll(); }, []);

  const ack = async (id: string) => {
    const { error } = await supabase.from("risk_alerts").update({ acknowledged_at: new Date().toISOString() }).eq("id", id);
    if (error) toast({ title: "Failed", description: error.message, variant: "destructive" });
    else fetchAll();
  };

  const runEngine = async () => {
    setRunning(true);
    try {
      const { error } = await supabase.functions.invoke("risk-alerts-engine", { body: {} });
      if (error) throw error;
      toast({ title: "Alerts engine ran", description: "Notifications delivered." });
      fetchAll();
    } catch (e: any) {
      toast({ title: "Failed", description: e.message, variant: "destructive" });
    } finally { setRunning(false); }
  };

  return (
    <DashboardLayout>
      <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold text-foreground flex items-center gap-2"><Bell className="h-6 w-6 text-primary" />Alerts & Notifications</h1>
          <p className="text-sm text-muted-foreground">Recent risk alerts generated by the engine.</p>
        </div>
        <Button onClick={runEngine} disabled={running} className="gap-2">
          {running ? <Loader2 className="h-4 w-4 animate-spin" /> : <AlertTriangle className="h-4 w-4" />}
          Run Alerts Engine
        </Button>
      </div>

      <Card><CardHeader><CardTitle className="text-base">{alerts.length} alerts</CardTitle></CardHeader>
        <CardContent>
          {loading ? <div className="flex justify-center py-10"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div>
            : !alerts.length ? <p className="text-center text-muted-foreground py-10">No alerts. Click Run Alerts Engine.</p>
            : <div className="overflow-x-auto"><Table>
              <TableHeader><TableRow><TableHead>Severity</TableHead><TableHead>Type</TableHead><TableHead>Message</TableHead><TableHead>Created</TableHead><TableHead>Status</TableHead><TableHead></TableHead></TableRow></TableHeader>
              <TableBody>{alerts.map((a) => (
                <TableRow key={a.id}>
                  <TableCell><Badge variant={a.severity === "CRITICAL" ? "destructive" : "secondary"}>{a.severity}</Badge></TableCell>
                  <TableCell className="text-xs">{a.alert_type}</TableCell>
                  <TableCell className="max-w-md text-sm">{a.message}</TableCell>
                  <TableCell className="text-xs text-muted-foreground">{new Date(a.created_at).toLocaleString()}</TableCell>
                  <TableCell>{a.acknowledged_at ? <Badge variant="outline" className="gap-1"><Check className="h-3 w-3" />Ack</Badge> : <Badge variant="secondary">Open</Badge>}</TableCell>
                  <TableCell>{!a.acknowledged_at && <Button size="sm" variant="ghost" onClick={() => ack(a.id)}>Acknowledge</Button>}</TableCell>
                </TableRow>
              ))}</TableBody>
            </Table></div>}
        </CardContent>
      </Card>
    </DashboardLayout>
  );
}
